layout_spectrum: 1
color:
  saturation: 0.5988185
  lightness: 0.6911923
  brandStrength: 0.6911923
  brandColors:
    - '#D0DEE9'
    - '#05060B'
    - '#91ABB6'
    - '#427F9A'
    - '#0F1E42'
  rhythmicContrast: 0.3786251
typography_spectrum: 0.1810627
name: Thecloudbook
